default:
  interruptible: false
stages:
  - tag
  - publish

######
# Tag stage
tag:
  image: harbor.containers.wurnet.nl/proxy-cache/library/node:20.10.0
  stage: tag
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release@23.0.8 @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/gitlab @semantic-release/git @semantic-release/npm @semantic-release/release-notes-generator conventional-changelog conventional-changelog-conventionalcommits@7.0.2
  script:
    - semantic-release
  when: on_success
  only:
    - main
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/

######
# Publish stage
# build a new container
include:
  - project: 'soilwise/soilwise-docs'
    file: 'DestinationHarbor.yml'
#    file: 'DestinationHarborWeTransform.yml'
